### ISSUE TITLE
[BUG] - Random crash

### ISSUE THREAD

**Issue by gabriel20xx** [zaneschepke/wgtunnel#235]
**Describe the bug**
The app crashed randomly today. This is the error:

[Device Brand]: POCO
[Device Model]: M2012K11AG
[Display]: AP1A.240505.005
[Android Version]: 14
[Android API Level]: 34
[System Locale]: en_GB
[Process ID]: 13074
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.zaneschepke.wireguardautotunnel
[Version Name]: 3.4.6
[Version Code]: 34600
[Target SDK]: 34
[Min SDK]: 26
[Error Type]: JVM
[Crash Time]: 2024-06-07T17:03:00.554
[Stack Trace]:
java.io.FileNotFoundException: /data/user/0/com.zaneschepke.wireguardautotunnel/cache/tmp/Gabriels Phone.conf: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at U3.e.d(Unknown Source:60)
	at U3.e.b(Unknown Source:86)
	at m4.h.a(Unknown Source:336)
	at m4.e.r(Unknown Source:85)
	at U4.a.t(Unknown Source:8)
	at n5.F.run(Unknown Source:114)
	at G2.e.run(Unknown Source:245)
	at u5.i.run(Unknown Source:2)
	at u5.a.run(Unknown Source:91)
	Suppressed: s5.g: [l0{Cancelling}@79690ca, Dispatchers.Main.immediate]
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8389)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 10 more

**Smartphone (please complete the following information):**

- Device: Poco F3
- Android Version: Android 14
- App Version: 3.4.6

**To Reproduce**

It happend randomly 

**Expected behavior**
App should not have crashed

**Screenshots (Only if necessary)**

**Additional context**
No

**Comment by zaneschepke** [comment]
Any additional details on what you were doing when the app crashed? 

Also, are you using kernel mode?

**Comment by gabriel20xx** [comment]
Hasn't happen in a while so I close this issue
