### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by teemue** [zaneschepke/wgtunnel#40]
I'm not sure if this is related to #37:
After updating from 3.0.0 to 3.0.2 or 3.0.3 WGTunnel crashes right after starting the app. The home screen flashes.
Phone is OnePlus Nord 5G N10, Android 11.
Trier to clear app data.

 Here's the log:
```
10-06 14:05:07.649 18407 28649 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
10-06 14:05:07.649 18407 28649 E AndroidRuntime: Process: com.zaneschepke.wireguardautotunnel, PID: 18407
10-06 14:05:07.649 18407 28649 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgo
t to update the version number. You can simply fix this by increasing the version number. Expected identity hash: ba86153e6fb0b823197b987239b03e64, found: 8aebda3e
5fb876f17654b7080d2356e0
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at k3.d0.e(Unknown Source:101)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at o3.e.onOpen(Unknown Source:15)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at o3.e.c(Unknown Source:4)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at o3.e.f(Unknown Source:63)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at o3.e.a(Unknown Source:23)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at o3.f.v(Unknown Source:9)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at k3.c0.j(Unknown Source:12)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at k2.d.F0(Unknown Source:11)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at d5.c.a(Unknown Source:31)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at d5.c.call(Unknown Source:116)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at k3.b.l(Unknown Source:84)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at i6.a.p(Unknown Source:8)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at x6.e0.run(Unknown Source:114)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
10-06 14:05:07.649 18407 28649 E AndroidRuntime:        Suppressed: c7.g: [k1{Cancelling}@148b055, Dispatchers.IO]
```

**Comment by zaneschepke** [comment]
Hello! Yes, this is the same issue as #37. It seems like somehow the phone storage is not getting fully cleared. Could you try clear data, clear cache, uninstall, restart phone, reinstall?

**Comment by teemue** [comment]
Did that and now it works.
