### ISSUE TITLE
[BUG] - Quick tile does not work without app being already opened.

### ISSUE THREAD

**Issue by KDBal** [zaneschepke/wgtunnel#491]
**Describe the bug**
Starting with version 3.6.2 VPN can no longer be started with quick tile without app itself being already opened.
If app is opened everything works as expected.
Versions 3.6.1 and below also work as expected.

**Smartphone (please complete the following information):**

- Device: Xiaomi Redmi Note 8T
- Android Version: Android 11 (MIUI 12.5.6)
- App Version 3.6.2 and 3.6.3
- Backend: Userspace

**To Reproduce**

1. Import configuration
2. Set primary tunnel
3. Close app
4. Tap quick tile.

**Expected behavior**
VPN starts

**Actual behavior**
VPN does not start

**Comment by eternal-sorrow** [comment]
I can confirm this bug on LineageOS 21.

**Comment by zaneschepke** [comment]
Hello! Can either of you see anything in the logs when this happens?

I am unable to replicate. 

I wonder if this is related to a bug that was introduced in 3.6.2. If one of you is willing to uninstall and reinstall the app I have a feeling that will fix this issue.

**Comment by eternal-sorrow** [comment]
Just tried it - didn't fix.

**Comment by eternal-sorrow** [comment]
>Hello! Can either of you see anything in the logs when this happens?

Where can I see those logs?

**Comment by zaneschepke** [comment]
> > Hello! Can either of you see anything in the logs when this happens?
> 
> Where can I see those logs?

On the support screen, enable logging and then you will see an option to navigate to a logs screen

**Comment by eternal-sorrow** [comment]
I see a crash. Is the backtrace safe to post? Could it contain some secret info?

Here is a (I think) a key line from the crash backtrace. I edited it a little:
```
E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.zaneschepke.wireguardautotunnel.service.foreground.TunnelBackgroundService: java.lang.SecurityException: Starting FGS with type systemExempted callerApp=ProcessRecord{<EDITED>} targetSDK=35 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_SYSTEM_EXEMPTED] any of the permissions allOf=false [android.permission.SCHEDULE_EXACT_ALARM, android.permission.USE_EXACT_ALARM, android:activate_vpn] 
```

**Comment by zaneschepke** [comment]
Is there any change with the latest nightly version or still the same error?

**Comment by eternal-sorrow** [comment]
I'll leave testing the Nightly it to someone else. I only install apps from F-droid.

**Comment by dkoppenh** [comment]
Long pressing the quick tiles opens the app for me, but clicking on the "auto tunnel service monitoring state changes" persistent notification does nothing. It used to open the app. I'm on fdroid release 3.6.3, upgraded directly from 3.6.0.

Should I open a new issue? 

Thanks again for your work on this excellent program.

**Comment by eternal-sorrow** [comment]
>Long pressing the quick tiles opens the app for me

Yes, that works for me too, but I don't want to open the app, I want to be able to switch VPN on and off without opening the app. That's what Quick Settings tiles are about.

**Comment by KDBal** [comment]
> Is there any change with the latest nightly version or still the same error?

In the version 3.6.4-0201523-nightly the issue still persists.

**Comment by KDBal** [comment]
Not sure if this is the correct log, but her it is:

```
--------- beginning of crash
         1734698144.758 18045 18131 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-7
         1734698144.758 18045 18131 E AndroidRuntime: Process: com.zaneschepke.wireguardautotunnel.nightly, PID: 18045
         1734698144.758 18045 18131 E AndroidRuntime: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.zaneschepke.wireguardautotunnel.nightly/org.amnezia.awg.backend.GoBackend$VpnService }: app is in background uid UidRecord{4710dd5 u0a1024 CEM  idle change:cached procs:1 seq(0,0,0)}
         1734698144.758 18045 18131 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1725)
         1734698144.758 18045 18131 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1680)
         1734698144.758 18045 18131 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:731)
         1734698144.758 18045 18131 E AndroidRuntime: 	at p6.b.b(Unknown Source:24)
         1734698144.758 18045 18131 E AndroidRuntime: 	at p6.b.c(Unknown Source:63)
         1734698144.758 18045 18131 E AndroidRuntime: 	at B4.y.o(Unknown Source:94)
         1734698144.758 18045 18131 E AndroidRuntime: 	at B4.s.m(Unknown Source:108)
         1734698144.758 18045 18131 E AndroidRuntime: 	at C5.a.u(Unknown Source:8)
         1734698144.758 18045 18131 E AndroidRuntime: 	at V5.E.run(Unknown Source:112)
         1734698144.758 18045 18131 E AndroidRuntime: 	at D1.a.run(Unknown Source:121)
         1734698144.758 18045 18131 E AndroidRuntime: 	at c6.j.run(Unknown Source:2)
         1734698144.758 18045 18131 E AndroidRuntime: 	at c6.a.run(Unknown Source:91)
         1734698144.758 18045 18131 E AndroidRuntime: 	Suppressed: a6.g: [o0{Cancelling}@4794da4, Dispatchers.Default]
--------- beginning of main
         1734698144.897 18045 18131 I Process : Sending signal. PID: 18045 SIG: 9
         1734698146.182 18230 18230 E otunnel.nightl: Unknown bits set in runtime_flags: 0x800000
         1734698146.187 18230 18230 E otunnel.nightl: Not starting debugger since process cannot load the jdwp agent.
         1734698146.297 18230 18230 I Perf    : Connecting to perf service.
         1734698146.317 18230 18230 D NetworkSecurityConfig: No Network Security Config specified, using platform default
         1734698146.318 18230 18230 D NetworkSecurityConfig: No Network Security Config specified, using platform default
         1734698146.765 18230 18271 D AmneziaWG/GoBackend: Set backend state
         1734698146.765 18230 18271 D AmneziaWG/GoBackend: Requesting service activation
         1734698151.334 18230 18252 I otunnel.nightl: Waiting for a blocking GC ProfileSaver
         1734698151.359 18230 18252 I otunnel.nightl: WaitForGcToComplete blocked ProfileSaver on AddRemoveAppImageSpace for 25.438ms
         1734698151.419 18230 18244 I otunnel.nightl: WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 58.876ms
         1734698151.590 18230 18557 D ProfileInstaller: Skipping profile installation for com.zaneschepke.wireguardautotunnel.nightly
         1734698168.505 18230 18230 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
         1734698168.586 18230 18230 D DecorView[]: getWindowModeFromSystem  windowmode is 1
         1734698168.586 18230 18230 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
         1734698168.983 18230 18230 D DecorView[]: getWindowModeFromSystem  windowmode is 1
         1734698169.024 18230 18892 I AdrenoGLES-0: QUALCOMM build                   : 03e27f8, I326e6aff90
         1734698169.024 18230 18892 I AdrenoGLES-0: Build Date                       : 11/02/20
         1734698169.024 18230 18892 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.04
         1734698169.024 18230 18892 I AdrenoGLES-0: Local Branch                     : mybrancheb1d781c-1a78-f1f4-8c78-ac1f6bcc2cee
         1734698169.024 18230 18892 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r116-rel
         1734698169.024 18230 18892 I AdrenoGLES-0: Remote Branch                    : NONE
         1734698169.024 18230 18892 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
         1734698169.024 18230 18892 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
         1734698169.024 18230 18892 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
--------- beginning of system
         1734698169.039 18230 18230 W Looper  : PerfMonitor doFrame : time=382ms vsyncFrame=0 latency=8ms procState=2 historyMsgCount=3 (msgIndex=1 wall=233ms seq=12 running=122ms runnable=28ms io=43ms late=1ms h=android.app.ActivityThread$H w=159)
         1734698169.062 18230 18892 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
         1734698169.143 18230 18230 W Looper  : PerfMonitor doFrame : time=67ms vsyncFrame=0 latency=410ms procState=2 historyMsgCount=4 (msgIndex=1 wall=382ms seq=15 running=285ms runnable=10ms io=22ms late=8ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
         1734698169.146 18230 18905 D AmneziaWG/GoBackend: Set backend state
         1734698169.147 18230 18905 D AmneziaWG/GoBackend: Requesting service activation
         1734698169.265 18230 18230 D DecorView[]: getWindowModeFromSystem  windowmode is 1
         1734698169.292 18230 18905 D AmneziaWG/GoBackend: Service is now active
         1734698169.405 18230 18892 E LB      : fail to open file: No such file or directory
         1734698170.686 18230 18230 V MiuiFrameworkFactory: get AllImpl object = android.common.MiuiFrameworkFactoryImpl@8b0e926
         1734698170.692 18230 18230 W MirrorManager: this model don't Support

```

**Comment by KDBal** [comment]
@zaneschepke 
The issue persists in 3.6.5

**Comment by R7010A** [comment]
Additional info to this issue:
When I am in my own WiFi (Auto tunnel on) the **tunnel control toggle** is set to off. At night, the provider forcibly disconnects the Internet, so the phone is no longer in WiFi for a short time. After reconnecting, however, the toggle remains on even though wg tunnel correctly disabled the vpn connection. By turning the WiFi off and on manually, the toggle works correctly again. "Restart on PING error" is disabled. 
Error occurs since v3.6.5.

**Comment by zaneschepke** [comment]
I've tried to replicate this bug on a few different devices and I am still not able to do so. 

I made some changes that might have helped though if someone can please try the latest nightly build to see if that helps.

**Comment by zaneschepke** [comment]
Sorry, there was an issue with the nightly version, but it is now available.
